POST http://localhost:3000/api/users
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjhjZTRlMTI3YzgwZDMxNTQ0ODY4YTRkIiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTc1ODM1MDkxNSwiZXhwIjoxNzU4MzU0NTE1fQ.hwupHBtwFKLek2q4jp3QKDY9lBoqx1V1Epvqcte_xJc 
Content-Type: application/json

{   
    "first_name":"Iroda",
    "last_name":"Muminova",
    "age":20,
    "username":"iroda",
    "role":"admin",
    "password":"1234"
}

###
GET http://localhost:3000/api/users
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjhjZTRlMTI3YzgwZDMxNTQ0ODY4YTRkIiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTc1ODM1MDkxNSwiZXhwIjoxNzU4MzU0NTE1fQ.hwupHBtwFKLek2q4jp3QKDY9lBoqx1V1Epvqcte_xJc 

###
GET http://localhost:3000/api/users/65009310bce7f2521e2cfc0d
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjhjZTRlMTI3YzgwZDMxNTQ0ODY4YTRkIiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTc1ODM1MDkxNSwiZXhwIjoxNzU4MzU0NTE1fQ.hwupHBtwFKLek2q4jp3QKDY9lBoqx1V1Epvqcte_xJc 
###
DELETE http://localhost:3000/api/users/64f871e6f3fd6493b2acab99
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjhjZTRlMTI3YzgwZDMxNTQ0ODY4YTRkIiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTc1ODM1MDkxNSwiZXhwIjoxNzU4MzU0NTE1fQ.hwupHBtwFKLek2q4jp3QKDY9lBoqx1V1Epvqcte_xJc 

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
     "username":"iroda",
    "password":"1234"
}

###
GET http://localhost:3000/api/users/me
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjhjZTRlMTI3YzgwZDMxNTQ0ODY4YTRkIiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTc1ODM1MDkxNSwiZXhwIjoxNzU4MzU0NTE1fQ.hwupHBtwFKLek2q4jp3QKDY9lBoqx1V1Epvqcte_xJc 


###
PATCH http://localhost:3000/api/users/68ce4e127c80d31544868a4d
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjhjZTRlMTI3YzgwZDMxNTQ0ODY4YTRkIiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTc1ODM1MDkxNSwiZXhwIjoxNzU4MzU0NTE1fQ.hwupHBtwFKLek2q4jp3QKDY9lBoqx1V1Epvqcte_xJc 
Content-Type: application/json

{
    "username":"iroda"
}

###
PATCH http://localhost:3000/api/users/me
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjhjZTRlMTI3YzgwZDMxNTQ0ODY4YTRkIiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTc1ODM1MDkxNSwiZXhwIjoxNzU4MzU0NTE1fQ.hwupHBtwFKLek2q4jp3QKDY9lBoqx1V1Epvqcte_xJc .eyJ1c2VyIjp7ImlkIjoiNjUwMDkzMTBiY2U3ZjI1MjFlMmNmYzBjIiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NDUzNzU1MiwiZXhwIjoxNjk0OTgwMzUyfQ.yZ84KOHeuwvhV5HUsqOpSmGWnpSt8nAln8a37iEdj_o
Content-Type: application/json

{
    "first_name":"admin002"
}